### PR TITLE
feat: add basic auth options

### PR DESCRIPTION
**Pull request by marionebl**
- add second parameter to constructor
- implement usage of òpts.username, opts.password

### CODE REVIEW

**Comment by marionebl** [comment]
Any issues with this?

**Comment by marionebl** [comment]
Any news?

**Comment by pnedelko** [comment]
@marionebl sorry for the delay. I'd like to implement this in a bit different way. Fix is already coming. As a workaround you can pass Marathon url as `http://user:pass@host:port`. This works for us perfectly well.

**Comment by pnedelko** [comment]
@marionebl version 1.0.3 has been published. Have a look at documentation here: https://github.com/elasticio/marathon-node#options.

**Pull request closed without merging**
